ECK test in gh actions

diff --git a/.github/workflows/trigger-e2e-tests.yml b/.github/workflows/trigger-e2e-tests.yml
--- a/.github/workflows/trigger-e2e-tests.yml
+++ b/.github/workflows/trigger-e2e-tests.yml
@@ -34,3 +34,16 @@ jobs:
         run: |
           aws configure set region eu-west-1
           aws s3 cp results/videos/ s3://readonlyrest-data/e2e-tests/build_${{ github.run_id }}/${{ matrix.env }}/${{ matrix.version }}/ --recursive
+  
+  determine-final-result-of-e2e-tests:
+    needs: e2e-tests  
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check if any job failed
+        run: |
+          if [ "${{ needs.e2e-tests.result }}" != "success" ]; then
+            echo "One or more tests failed."
+            exit 1
+          else
+            echo "All tests passed."
+          fi
