wip
wip

wip

wip

kibana ssl

wip

wip

wip

wip

cy-task-verification

fix issues

improvements

wip

ECK test in gh actions

ECK test in gh actions

fix

ECK test in gh actions

ECK test in gh actions

ECK test in gh actions

ECK test in gh actions

ECK test in gh actions

ECK test in gh actions

ECK test in gh actions

ECK test in gh actions

ECK test in gh actions

ECK test in gh actions

ECK test in gh actions

ECK test in gh actions

ECK test in gh actions

diff --git a/.github/workflows/trigger-e2e-tests.yml b/.github/workflows/trigger-e2e-tests.yml
--- a/.github/workflows/trigger-e2e-tests.yml
+++ b/.github/workflows/trigger-e2e-tests.yml
@@ -12,12 +12,18 @@ jobs:
     runs-on: ubuntu-latest
     strategy:
       matrix:
-        version: [8x, 7x]
+        version: ["8.15.2", "7.17.24"]
+        env: [docker, eck] 
+    continue-on-error: true
     steps:
       - name: Checkout code
         uses: actions/checkout@v2
+      - name: Set up Node.js
+        uses: actions/setup-node@v3
+        with:
+          node-version: '20'  
       - name: Run tests
-        run: ./run-${{ matrix.version }}.sh
+        run: ./run-env-and-tests.sh ${{ matrix.version }} ${{ matrix.env }}
         env:
           ROR_ACTIVATION_KEY: ${{ secrets.ROR_KBN_LICENSE }}
       - name: S3 Upload Videos & show logs
@@ -27,4 +33,25 @@ jobs:
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         run: |
           aws configure set region eu-west-1
-          aws s3 cp results/videos/ s3://readonlyrest-data/e2e-tests/build_${{ github.run_id }}/${{ matrix.version }}/ --recursive
+          aws s3 cp results/videos/ s3://readonlyrest-data/e2e-tests/build_${{ github.run_id }}/${{ matrix.env }}/${{ matrix.version }}/ --recursive
+  
+  determine-final-result-of-e2e-tests:
+    needs: e2e-tests 
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check if any matrix job failed
+        run: |
+          FAILED=false
+          for job in  ${{ toJson(needs.e2e-tests.outputs.matrix) }}; do
+            if [ "$job.result" != "success" ]; then
+              FAILED=true
+              echo "Job ${job} failed."
+            fi
+          done
+          
+          if [ "$FAILED" = true ]; then
+            echo "One or more tests failed."
+            exit 1
+          else
+            echo "All tests passed."
+          fi
